site_name: Notes
site_url: https://cpbnotes.pages.dev

repo_url: "https://github.com/naoisehayes/notes"
repo_name: "GitHub"
edit_uri: "/"


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list

theme:
    name: null
    custom_dir: 'custom_theme/'
    highlightjs: true
    static_templates:
            - 404.html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
