site_name: Notes
site_url: https://cpbnotes.pages.dev

repo_url: "https://github.com/naoisehayes/notes"
repo_name: "GitHub"
edit_uri: "/"


markdown_extensions:
  - attr_list
theme:
    name: null
    custom_dir: 'custom_theme/'
    highlightjs: true
    static_templates:
            - 404.html
